(function(a,h){"object"===typeof exports?module.exports=h():"function"===typeof define&&define.amd?define([],h):a.HelloWorld=h})(this,function(){var a={load:function(){},loadAnnex:function(){},singletons:{nodejsTools:{}},getAjax:function(){var b=null;try{b=new XMLHttpRequest}catch(a){for(var c=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0;d<c.length;d++)try{b=new ActiveXObject(c[d])}catch(e){}}return b},initSuper:function(b,a){var c;c=a&&a.lzrGeneralization_?a.lzrGeneralization_.prototype.super_:
b.super_;for(var d=0;d<c.length;d++)c[d].call(b,{lzrGeneralization_:c[d]})},setObj:function(b,a){for(var c in a){var d=b[c];if(void 0!==d){var e=a[c];switch(this.getClassName(d)){case "LZR.Base.Val":case "LZR.Base.Val.Ctrl":switch(this.getClassName(e)){case "LZR.Base.Val":case "LZR.Base.Val.Ctrl":b[c]=e;break;default:d.set(e,!1)}break;default:b[c]=e}}}},getSingleton:function(b,f,c){var d;c?(d=a.singletons.nodejsTools[c],d||(d=require(c),a.singletons.nodejsTools[c]=d)):(d=a.singletons[b.prototype.className_],
d||(d=new b(f),a.singletons[d.className_]=d));return d},clone:function(b,a,c,d){var e=this.getClassName(b);switch(e){case "number":case "string":case "boolean":case "function":case "null":case "undefined":a=b;break;case "Date":a=new Date(b.valueOf());break;case "Array":if(null===a||void 0===a)a=[];for(e in b)a[e]=d?this.clone(b[e],a[e],c,d):b[e];break;default:if(0===e.indexOf("LZR.")&&b!==b.constructor.prototype)if(b.clone)a=b.clone(a);else{c=b.constructor.prototype;d={};for(e in b)void 0===c[e]&&
(d[e]=a?a[e]?a[e]:this.clone(b[e],!0):b[e]);a=new b.constructor(d)}else{if(null===a||void 0===a)a={};for(e in b)a[e]=c?this.clone(b[e],a[e],c,d):b[e]}}return a},getClassName:function(b){if(null===b)return"null";var a=typeof b;if("object"!=a||(a=b.className_))return a;a=Object.prototype.toString.apply(b);a=a.substring(8,a.length-1);if("Object"==a){var c=b.constructor;if(c==Object)return a;if(b.prototype&&"classname"in b.prototype.constructor&&"string"==typeof b.prototype.constructor.classname)return c.prototype.classname}return a},
del:function(b,a){delete b[a]}};a.load(["LZR"],"LZR.HTML");a.HTML=function(b){b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.HTML.prototype.className_="LZR.HTML";a.HTML.prototype.version_="1.0";a.load(null,"LZR.HTML");a.HTML.logger=null;a.HTML.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.HTML.prototype.hdObj_=function(){};a.HTML.createLog=function(){this.logger||(this.logger=document.getElementById("LZR_LOG"),this.logger||(this.logger=
document.createElement("pre"),this.logger.id="LZR_LOG",document.body.children.length?document.body.insertBefore(this.logger,document.body.children[0]):document.body.appendChild(this.logger)))};a.HTML.log=function(b){this.createLog();this.logger.innerHTML=b};a.HTML.alog=function(b){this.createLog();this.logger.innerHTML+=b;this.logger.innerHTML+="<br>"};a.load(["LZR.HTML"],"LZR.HTML.Base");a.HTML.Base=function(b){b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};
a.HTML.Base.prototype.className_="LZR.HTML.Base";a.HTML.Base.prototype.version_="1.0";a.load(null,"LZR.HTML.Base");a.HTML.Base.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.HTML.Base.prototype.hdObj_=function(){};a.load(["LZR"],"LZR.Base");a.Base=function(b){b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.Base.prototype.className_="LZR.Base";a.Base.prototype.version_="1.0";a.load(null,"LZR.Base");a.Base.prototype.init_=function(b){b&&
(a.setObj(this,b),this.hdObj_(b))};a.Base.prototype.hdObj_=function(){};a.loadAnnex({JSON:"/Lib/Util/JSON.js"});a.load(["LZR.Base"],"LZR.Base.Json");a.Base.Json=function(b){this.src=JSON;b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.Base.Json.prototype.className_="LZR.Base.Json";a.Base.Json.prototype.version_="1.0";a.load(null,"LZR.Base.Json");a.Base.Json.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.Base.Json.prototype.hdObj_=function(){};
a.Base.Json.prototype.toJson=function(b){return this.src.stringify(b)};a.Base.Json.prototype.toObj=function(b){return this.src.parse(b)};a.load(["LZR"],"LZR.Util");a.Util=function(b){b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.Util.prototype.className_="LZR.Util";a.Util.prototype.version_="1.0";a.load(null,"LZR.Util");a.Util.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.Util.prototype.hdObj_=function(){};a.Util.prototype.bind=function(b,
a,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c,g=[];for(c=0;c<d.length;c++)g.push(d[c]);for(c=0;c<arguments.length;c++)g.push(arguments[c]);return a.apply(b,g)}};a.Util.prototype.supCall=function(b,a,c,d){for(var e=Array.prototype.slice.call(arguments,3),g=arguments.callee.caller.arguments,g=(g=g[g.length-1])&&g.lzrGeneralization_?g.lzrGeneralization_.prototype.super_:b.super_,h=g[a].prototype[c],i=h.length;e.length<i;)e.push(void 0);e.push({lzrGeneralization_:g[a]});return h.apply(b,
e)};a.Util.prototype.exist=function(b,a){for(var c=a.split("."),d=0;d<c.length;d++){if(void 0===b||null===b)return;b=b[c[d]]}return b};a.Util.prototype.sleep=function(b){for(var a=new Date,b=a.getTime()+b;!(a=new Date,a.getTime()>b););};a.load(["LZR.Base"],"LZR.Base.Str");a.Base.Str=function(b){b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.Base.Str.prototype.className_="LZR.Base.Str";a.Base.Str.prototype.version_="1.0";a.load(null,"LZR.Base.Str");a.Base.Str.prototype.init_=
function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.Base.Str.prototype.hdObj_=function(){};a.Base.Str.prototype.format=function(b,a,c){var b=b+"",d=b.length;if(a>d){d=a-d;for(a=0;a<d;a++)b=c+b}return b};a.Base.Str.prototype.startWith=function(b,a){return RegExp("^"+a).test(b)};a.Base.Str.prototype.endWith=function(b,a){return RegExp(a+"$").test(b)};a.load(["LZR.Util","LZR.Base","LZR.Base.Str","LZR.Base.CallBacks.CallBack"],"LZR.Base.CallBacks");a.Base.CallBacks=function(b){this.autoEvent=this.enableEvent=
!0;this.obj=this;this.count=0;this.exe=null;this.id=0;this.funs={};this.utLzr=a.getSingleton(a.Util);b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.Base.CallBacks.prototype.className_="LZR.Base.CallBacks";a.Base.CallBacks.prototype.version_="1.0";a.load(null,"LZR.Base.CallBacks");a.Base.CallBacks.prototype.init_=function(b){this.exe=this.utLzr.bind(this,this.execute);b&&(a.setObj(this,b),this.hdObj_(b))};a.Base.CallBacks.prototype.hdObj_=function(){};a.Base.CallBacks.prototype.add=
function(b,f,c){if(void 0===f||null===f)f=this.id;this.id++;void 0===this.funs[f]&&this.count++;b={name:f,fun:b};!0===c&&(b.selfInfo=!0);this.funs[f]=new a.Base.CallBacks.CallBack(b);return f};a.Base.CallBacks.prototype.del=function(b){var f=this.funs[b];void 0!==f&&(a.del(this.funs,b),this.count--);return f};a.Base.CallBacks.prototype.execute=function(){var b=!0;if(this.enableEvent)for(var a in this.funs)switch(a){case "length":break;default:if(this.funs[a].enableEvent){var c;this.funs[a].selfInfo?
(c=Array.prototype.slice.call(arguments),c.push({id:"selfInfo",root:this,parent:this.funs,self:this.funs[a],nam:this.funs[a].name})):c=arguments;!1===this.funs[a].fun.apply(this.obj,c)&&(b=!1)}else this.funs[a].enableEvent=this.funs[a].autoEvent}else this.enableEvent=this.autoEvent;return b};a.load(["LZR.Base.CallBacks"],"LZR.Base.CallBacks.CallBack");a.Base.CallBacks.CallBack=function(a){this.name="";this.autoEvent=this.enableEvent=!0;this.selfInfo=!1;this.fun=null;a&&a.lzrGeneralization_?a.lzrGeneralization_.prototype.init_.call(this):
this.init_(a)};a.Base.CallBacks.CallBack.prototype.className_="LZR.Base.CallBacks.CallBack";a.Base.CallBacks.CallBack.prototype.version_="1.0";a.load(null,"LZR.Base.CallBacks.CallBack");a.Base.CallBacks.CallBack.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.Base.CallBacks.CallBack.prototype.hdObj_=function(){};a.load(["LZR.Base"],"LZR.Base.InfEvt");a.Base.InfEvt=function(){this.evt={}};a.Base.InfEvt.prototype.className_="LZR.Base.InfEvt";a.Base.InfEvt.prototype.version_="1.0";
a.load(null,"LZR.Base.InfEvt");a.Base.InfEvt.prototype.setEventObj=function(a){this.setEventObjRecursion(this.evt,a)};a.Base.InfEvt.prototype.setEventObjRecursion=function(a,f){for(var c in a)"LZR.Base.CallBacks"===a.className_?a[c].obj=f:this.setEventObjRecursion(a[c],f)};a.load(["LZR.HTML.Base","LZR.Base.Json","LZR.Util","LZR.Base.CallBacks","LZR.Base.InfEvt"],"LZR.HTML.Base.Ajax");a.HTML.Base.Ajax=function(b){a.Base.InfEvt.call(this);this.ajax=a.getAjax();this.utJson=a.getSingleton(a.Base.Json);
this.utLzr=a.getSingleton(a.Util);this.evt.rsp=new a.Base.CallBacks;b&&b.lzrGeneralization_?b.lzrGeneralization_.prototype.init_.call(this):this.init_(b)};a.HTML.Base.Ajax.prototype=a.clone(a.Base.InfEvt.prototype,a.HTML.Base.Ajax.prototype);a.HTML.Base.Ajax.prototype.className_="LZR.HTML.Base.Ajax";a.HTML.Base.Ajax.prototype.version_="1.0";a.load(null,"LZR.HTML.Base.Ajax");a.HTML.Base.Ajax.prototype.init_=function(b){b&&(a.setObj(this,b),this.hdObj_(b))};a.HTML.Base.Ajax.prototype.hdObj_=function(){};
a.HTML.Base.Ajax.prototype.post=function(a,f,c,d,e){d?(this.ajax.onreadystatechange=this.utLzr.bind(this,this.onRsp),d=!0):d=!1;if(f&&"object"==typeof f){var g="",h;for(h in f)""!==g&&(g+="&"),g+=h,g+="=",g+=this.utJson.toJson(f[h]);f=g}try{e?this.ajax.open("GET",a,d):(this.ajax.open("POST",a,d),c||(c="application/x-www-form-urlencoded; charset=utf-8"),this.ajax.setRequestHeader("Content-Type",c)),this.ajax.send(f)}catch(i){return null}a=null;!d&&4==this.ajax.readyState&&(a=this.ajax.responseText);
return a};a.HTML.Base.Ajax.prototype.get=function(a,f){return this.post(a,null,null,f,!0)};a.HTML.Base.Ajax.prototype.asynPost=function(a,f,c){this.post(a,f,c,!0,!1)};a.HTML.Base.Ajax.prototype.onRsp=function(){4==this.ajax.readyState&&this.evt.rsp.execute(this.ajax.responseText,this.ajax.status)};a.HTML.Base.Ajax.prototype.abort=function(){this.ajax.abort()};var h={root:a,obj:{},bind:a.getSingleton(a.Util).bind,ajx:new a.HTML.Base.Ajax,utJson:a.getSingleton(a.Base.Json)};h.obj.root=h;var i=function(){this.addToCart=
function(a,f,c,d){f&&(a=this.tools.utJson.toJson({quick:0,spec:[],goods_id:a,number:f,parent:0}),this.tools.ajx.post("flow.php?step=add_to_cart","goods="+a),d&&(d=this.tools.utJson.toJson({quick:0,spec:[],goods_id:194,number:d,parent:0}),this.tools.ajx.post("flow.php?step=add_to_cart","goods="+d)),c&&(c=this.tools.utJson.toJson({quick:0,spec:[],goods_id:195,number:c,parent:0}),this.tools.ajx.post("flow.php?step=add_to_cart","goods="+c)),location.href="flow.php?step=cart")};this.dropFromCollection=
function(a,f){confirm(a)&&(location.href="user.php?act=delete_collection&collection_id="+f)}};i.prototype.tools=h;return i});
